### ISSUE TITLE
[Feature Request] /redo gpt-4 使用 gpt-4 模型重做上一次的对话

### ISSUE THREAD

**Issue by binux** [TBXark/ChatGPT-Telegram-Workers#185]
**其他信息**
这是一个 feature request。

因为 gpt-3.5 响应速度更快，价格更便宜，也足够使用的，所以我的模型默认都设置为 gpt-3.5。  
但是当回答不够好的时候，我希望能切换到 gpt-4 的模型。

我希望 /redo 能够接受一个参数 （或使用一个新的指令），将当前对话历史使用 gpt-4 模型 regenerate。（此功能可以通过 ENV 开启）

可选功能：权限限制谁可以使用 gpt-4 模型  
可选功能：接下去的对话继续使用 gpt-4 模型，并且可以切换回 gpt-3.5 （可以通过 ENV 开启？）

**Comment by TBXark** [comment]
和/redo在一起估计很难和正文分开，倒是可以加一个`/redo-gpt4`之类的命令。

**Comment by daiaji** [comment]
干脆连API也一起切换吧。
白嫖的ChatGPT 4 API也能搞到就是了。
加上自己的3.5 API也不是不能用。

**Comment by JDxiaojuju** [comment]
> 干脆连API也一起切换吧。 白痴的ChatGPT 4 API也能搞到就是了。 加上自己的3.5 API也不是不能用。

gpt4.0的api 在哪可搞可有传送门

**Comment by daiaji** [comment]
> > 干脆连API也一起切换吧。 白痴的ChatGPT 4 API也能搞到就是了。 加上自己的3.5 API也不是不能用。
> 
> gpt4.0的api 在哪可搞可有传送门

君的引用本当下手

**Comment by JDxiaojuju** [comment]
> > > 干脆连API也一起切换吧。白痴的ChatGPT 4 API也能搞到就是了。加上自己的3.5 API也不是不能用。
> > 
> > 
> > gpt4.0的api在哪可搞可有传送门
> 
> 君的引用本当下手

那个？？？？

**Comment by TBXark** [comment]
dev分支添加自定义指令功能，可以添加下面环境变量实现快速切换模型

```toml
CUSTOM_COMMAND_azure= '/setenvs {"AI_PROVIDER": "azure"}'
CUSTOM_COMMAND_workers = '/setenvs {"AI_PROVIDER": "workers"}'
CUSTOM_COMMAND_gpt3 = '/setenvs {"AI_PROVIDER": "openai", "CHAT_MODEL": "gpt-3.5-turbo"}'
CUSTOM_COMMAND_gpt4 = '/setenvs {"AI_PROVIDER": "openai", "CHAT_MODEL": "gpt-4"}'
```

之后在telegram中可以使用 `/gpt3`,`/gpt4`进行模型切换。 然后再进行`/redo`即可
