### ISSUE TITLE
如何实现在telegram客户端显示模型选择按钮或命令啊

### ISSUE THREAD

**Issue by shadowstar2023** [TBXark/ChatGPT-Telegram-Workers#226]
如何实现在telegram客户端显示模型选择按钮或命令啊

**Comment by TBXark** [comment]
可以修改这么文件添加新指令 https://github.com/TBXark/ChatGPT-Telegram-Workers/blob/master/src/command.js
考虑修改模型权限判断加上比较复杂，现在没有这个功能

**Comment by TBXark** [comment]
dev分支添加自定义指令功能，可以添加下面环境变量实现快速切换模型

```toml
CUSTOM_COMMAND_azure= '/setenvs {"AI_PROVIDER": "azure"}'
CUSTOM_COMMAND_workers = '/setenvs {"AI_PROVIDER": "workers"}'
CUSTOM_COMMAND_gpt3 = '/setenvs {"AI_PROVIDER": "openai", "CHAT_MODEL": "gpt-3.5-turbo"}'
CUSTOM_COMMAND_gpt4 = '/setenvs {"AI_PROVIDER": "openai", "CHAT_MODEL": "gpt-4"}'
```

之后在telegram中可以使用 `/gpt3`,`/gpt4`进行模型切换
